name: Build and deploy

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Install dependencies
        working-directory: .
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile

      - name: Build app
        working-directory: .
        run: pnpm generate

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Build artifact
          path: ./.output/public

      - name: Deploy to Cloudflare page
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./.output/public --project-name=afestupinanp --branch=main